backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - file: "content/pricing/_index.md"
        label: "Pricing"
        name: "pricing"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - file: "content/faq/_index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - file: "content/privacy-policy/_index.md"
        label: "Privacy Policy"
        name: "privacy_policy"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - file: "content/terms-conditions/_index.md"
        label: "Terms & Conditions"
        name: "terms"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }